include: https://raw.githubusercontent.com/JuliaGPU/gitlab-ci/master/templates/v6.yml

.run-test:
  script:
    - env JULIA_PKG_SERVER="" julia -e 'using Pkg; VERSION >= v"1.5-" && !isdir(joinpath(DEPOT_PATH[1], "registries", "General")) && Pkg.Registry.add("General")'
    - julia -e 'using Pkg; Pkg.add(name="Run", version="0.1")'
    - julia -e 'using Run; Run.prepare("test/environments/main")'
    - julia -e 'using Run; Run.test(project="test/environments/main")'

test:1:
  extends:
    - .julia:1
    - .test
    - .run-test
  tags:
      - nvidia

test:nightly:
  extends:
    - .julia:nightly
    - .test
    - .run-test
  tags:
      - nvidia
  allow_failure: true

coverage:
  extends:
    - .julia:1
    - .coverage
